---
spring:
  config.activate.on-profile: sqlite
  web.resources.static-locations: "file:./app"
  sql.init:
    mode: always
    schema-locations: classpath:schema-sqlite.sql
  datasource:
    url: "jdbc:sqlite:./db/sqlite.db"
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
      max-lifetime: 0
cds:
  sql.supportedLocales: "*"
  odata-v4:
    endpoint.path: "/api"
    lazy-i18n.enabled: true
